export const ADD_TO_CART = "ADD_TO_CART";
export const CHANGE_MESSAGE = "CHANGE_MESSAGE";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const CHANGE_QUANTITY_OF_PRODUCT = "CHANGE_QUANTITY_OF_PRODUCT";
